
export default [
    {
        artType: "Paintings",
        title: 'Image 1',
        description: 'Image description',
        images: [
            '/resources/images/paintings/image1_1.jpg',
            '/resources/images/paintings/image2_1.jpg',
            '/resources/images/paintings/image6_1.jpg',
            '/resources/images/paintings/image4_1.jpg'
        ],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Paintings",
        title: 'Image 2',
        description: 'Image description',
        images: ['/resources/images/paintings/image2_1.jpg', '/resources/images/paintings/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Paintings",
        title: 'Image 3',
        description: 'Image description',
        images: ['/resources/images/paintings/image3_1.jpg', '/resources/images/paintings/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Paintings",
        title: 'Image 4',
        description: 'Image description',
        images: ['/resources/images/paintings/image4_1.jpg', '/resources/images/paintings/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Paintings",
        title: 'Image 5',
        description: 'Image description',
        images: ['/resources/images/paintings/image5_1.jpg', '/resources/images/paintings/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Paintings",
        title: 'Image 6',
        description: 'Image description',
        images: ['/resources/images/paintings/image7_1.jpg', '/resources/images/paintings/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Paintings",
        title: 'Image 7',
        description: 'Image description',
        images: ['/resources/images/paintings/image3_1.jpg', '/resources/images/paintings/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Paintings",
        title: 'Image 8',
        description: 'Image description',
        images: ['/resources/images/paintings/image4_1.jpg', '/resources/images/paintings/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Paintings",
        title: 'Image 9',
        description: 'Image description',
        images: ['/resources/images/paintings/image5_1.jpg', '/resources/images/paintings/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Paintings",
        title: 'Image 10',
        description: 'Image description',
        images: ['/resources/images/paintings/image6_1.jpg', '/resources/images/paintings/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Paintings",
        title: 'Image 11',
        description: 'Image description',
        images: ['/resources/images/paintings/image7_1.jpg', '/resources/images/paintings/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Paintings",
        title: 'Image 12',
        description: 'Image description',
        images: ['/resources/images/paintings/image8_1.jpg', '/resources/images/paintings/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 13',
        description: 'Image description',
        images: ['/resources/images/photography/photo1_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 14',
        description: 'Image description',
        images: ['/resources/images/photography/photo2_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 15',
        description: 'Image description',
        images: ['/resources/images/photography/photo3_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 16',
        description: 'Image description',
        images: ['/resources/images/decors/photo4_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 17',
        description: 'Image description',
        images: ['/resources/images/decors/photo5_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 18',
        description: 'Image description',
        images: ['/resources/images/decors/photo4_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 19',
        description: 'Image description',
        images: ['/resources/images/decors/photo5_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 20',
        description: 'Image description',
        images: ['/resources/images/photography/photo6_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 21',
        description: 'Image description',
        images: ['/resources/images/photography/photo7_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 22',
        description: 'Image description',
        images: ['/resources/images/photography/photo8_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 23',
        description: 'Image description',
        images: ['/resources/images/photography/photo9_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: "Photography",
        title: 'Image 24',
        description: 'Image description',
        images: ['/resources/images/photography/photo10_1.jpg', '/resources/images/photography/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    }
];
