import { ArtType } from "@prisma/client";

export default [
    {
        artType: ArtType.Paintings,
        title: 'Image 1',
        description: 'Image description',
        images: [
            '/resources/artworks/image1_1.jpg',
            '/resources/artworks/image2_1.jpg',
            '/resources/artworks/image6_1.jpg',
            '/resources/artworks/image4_1.jpg'
        ],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Paintings,
        title: 'Image 2',
        description: 'Image description',
        images: ['/resources/artworks/image2_1.jpg', '/resources/artworks/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Paintings,
        title: 'Image 3',
        description: 'Image description',
        images: ['/resources/artworks/image3_1.jpg', '/resources/artworks/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Paintings,
        title: 'Image 4',
        description: 'Image description',
        images: ['/resources/artworks/image4_1.jpg', '/resources/artworks/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Paintings,
        title: 'Image 5',
        description: 'Image description',
        images: ['/resources/artworks/image5_1.jpg', '/resources/artworks/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Paintings,
        title: 'Image 6',
        description: 'Image description',
        images: ['/resources/artworks/image7_1.jpg', '/resources/artworks/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Paintings,
        title: 'Image 7',
        description: 'Image description',
        images: ['/resources/artworks/image3_1.jpg', '/resources/artworks/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Paintings,
        title: 'Image 8',
        description: 'Image description',
        images: ['/resources/artworks/image4_1.jpg', '/resources/artworks/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Paintings,
        title: 'Image 9',
        description: 'Image description',
        images: ['/resources/artworks/image5_1.jpg', '/resources/artworks/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Paintings,
        title: 'Image 10',
        description: 'Image description',
        images: ['/resources/artworks/image6_1.jpg', '/resources/artworks/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Paintings,
        title: 'Image 11',
        description: 'Image description',
        images: ['/resources/artworks/image7_1.jpg', '/resources/artworks/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Paintings,
        title: 'Image 12',
        description: 'Image description',
        images: ['/resources/artworks/image8_1.jpg', '/resources/artworks/image3_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 13',
        description: 'Image description',
        images: ['/resources/artworks/photo1_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 14',
        description: 'Image description',
        images: ['/resources/artworks/photo2_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 15',
        description: 'Image description',
        images: ['/resources/artworks/photo3_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 16',
        description: 'Image description',
        images: ['/resources/artworks/photo4_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 17',
        description: 'Image description',
        images: ['/resources/artworks/photo5_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 18',
        description: 'Image description',
        images: ['/resources/artworks/photo4_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 19',
        description: 'Image description',
        images: ['/resources/artworks/photo5_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 20',
        description: 'Image description',
        images: ['/resources/artworks/photo6_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 21',
        description: 'Image description',
        images: ['/resources/artworks/photo7_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 22',
        description: 'Image description',
        images: ['/resources/artworks/photo8_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 23',
        description: 'Image description',
        images: ['/resources/artworks/photo9_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    },
    {
        artType: ArtType.Photography,
        title: 'Image 24',
        description: 'Image description',
        images: ['/resources/artworks/photo10_1.jpg', '/resources/artworks/photo6_1.jpg'],
        medium: "Acrylic on canvas",
        dimension: "24*32",
        price: 1000,
        artistName: "Jinraj K R",
        isHidden: false,
        isSold: false,
    }
];
